[sources.my_source_id]
#encoding.codec = "json"
type = "kafka"
group_id = "consumer-group-name"
bootstrap_servers = "192.168.1.207:9092"
key_field = "procid"
#topics = [ "^(topic|prefix2)-.+" ]
topics = ["topic-1234"]
#topics = ["^(prefix1|prefix2)-.+", "topic-1234"]


[sinks.emit_syslog]
inputs = ["my_source_id"]
#inputs = ["generate_syslog"]
type = "console"
#encoding.codec = "json"
encoding.codec = "text"


[sinks.my_sink_id]
encoding.codec = "text"
type = "splunk_hec_logs"
inputs = [ "my_source_id" ]
endpoint = "https://192.168.1.203:8088"
#host_key = "hostname"
#indexed_fields = [ "procid" ]
compression = "none"
default_token = "c28d2dae-35d4-4714-bb25-0f71506ba3c8"
